<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{754979d4-a78e-4fca-8575-fe56d25142c0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    bButton : BOOL;   // Buton (giris) - simdilik sanal
    bLED    : BOOL;   // LED (cikis)  - simdilik sanal
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[bLED := bButton;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>